### ISSUE TITLE
Error with main.py

### ISSUE THREAD

**Issue by djtomcat** [synyster0fa7x/csgo-gsi-to-arduino#1]
Hi , hope someone can help me here
i just tried to test the script and when i try to start the main.py i get this error message : 

```
D:\csgo-gsi-to-arduino-develop\python>main.py
Traceback (most recent call last):
  File "D:\csgo-gsi-to-arduino-develop\python\main.py", line 16, in <module>
    __config__ = json.load(json_data_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 10 column 5 (char 179)
```

This is my config.json :

```
{
    "csgogsi":{
        "ip":"127.0.0.1",
        "port":"3000",
        "secret":"MY_SECRET_PHRASE"
    },
    "serial":{
        "port": "com3",
        "baudrate": 9600,
    }
}

```
The LED on the Arduino is on, so the code must be okay with the main.ino

Greetings
Björn

**Comment by anthonytournier** [comment]
Hello,

Remove the comma at the baudrate declaration line, it should worked after that. Sorry for the mistake i'll fix this soon.

**Comment by djtomcat** [comment]
Thank you for your fast reply :) It worked perfectly 
BTW: Does it only show green in main menu and yellow/blue for t/ct ? 
Are there future updates for integrating Bombtimer (even with real flashtimings slow/fast/faster) or maybe an health hud (green/yellow/red) ?

**Comment by anthonytournier** [comment]
I was planning to release some bomb timer effects and others animations, but i have no times to do it actually :(
